# Code for G

### This part creates all k-tuples

In [1]:
import numpy as np

t_l = [[(i,j) for i in range(1,13)] for j in range(1,13)]
t_l

[[(1, 1),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 1),
  (6, 1),
  (7, 1),
  (8, 1),
  (9, 1),
  (10, 1),
  (11, 1),
  (12, 1)],
 [(1, 2),
  (2, 2),
  (3, 2),
  (4, 2),
  (5, 2),
  (6, 2),
  (7, 2),
  (8, 2),
  (9, 2),
  (10, 2),
  (11, 2),
  (12, 2)],
 [(1, 3),
  (2, 3),
  (3, 3),
  (4, 3),
  (5, 3),
  (6, 3),
  (7, 3),
  (8, 3),
  (9, 3),
  (10, 3),
  (11, 3),
  (12, 3)],
 [(1, 4),
  (2, 4),
  (3, 4),
  (4, 4),
  (5, 4),
  (6, 4),
  (7, 4),
  (8, 4),
  (9, 4),
  (10, 4),
  (11, 4),
  (12, 4)],
 [(1, 5),
  (2, 5),
  (3, 5),
  (4, 5),
  (5, 5),
  (6, 5),
  (7, 5),
  (8, 5),
  (9, 5),
  (10, 5),
  (11, 5),
  (12, 5)],
 [(1, 6),
  (2, 6),
  (3, 6),
  (4, 6),
  (5, 6),
  (6, 6),
  (7, 6),
  (8, 6),
  (9, 6),
  (10, 6),
  (11, 6),
  (12, 6)],
 [(1, 7),
  (2, 7),
  (3, 7),
  (4, 7),
  (5, 7),
  (6, 7),
  (7, 7),
  (8, 7),
  (9, 7),
  (10, 7),
  (11, 7),
  (12, 7)],
 [(1, 8),
  (2, 8),
  (3, 8),
  (4, 8),
  (5, 8),
  (6, 8),
  (7, 8),
  (8, 8),
  (9, 8),
  (10, 8),
  (11, 8),
  (12, 8)],
 [(1, 9)

In [2]:
initial_colourings_G = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2]]

In [7]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c+1



In [8]:
Initial_colourings_G

{(1, 1): 3,
 (2, 1): 1,
 (3, 1): 1,
 (4, 1): 1,
 (5, 1): 2,
 (6, 1): 1,
 (7, 1): 1,
 (8, 1): 1,
 (9, 1): 2,
 (10, 1): 1,
 (11, 1): 1,
 (12, 1): 1,
 (1, 2): 1,
 (2, 2): 3,
 (3, 2): 1,
 (4, 2): 1,
 (5, 2): 1,
 (6, 2): 2,
 (7, 2): 1,
 (8, 2): 1,
 (9, 2): 1,
 (10, 2): 2,
 (11, 2): 1,
 (12, 2): 1,
 (1, 3): 1,
 (2, 3): 1,
 (3, 3): 3,
 (4, 3): 1,
 (5, 3): 1,
 (6, 3): 1,
 (7, 3): 2,
 (8, 3): 1,
 (9, 3): 1,
 (10, 3): 1,
 (11, 3): 2,
 (12, 3): 1,
 (1, 4): 1,
 (2, 4): 1,
 (3, 4): 1,
 (4, 4): 3,
 (5, 4): 1,
 (6, 4): 1,
 (7, 4): 1,
 (8, 4): 2,
 (9, 4): 1,
 (10, 4): 1,
 (11, 4): 1,
 (12, 4): 2,
 (1, 5): 2,
 (2, 5): 1,
 (3, 5): 1,
 (4, 5): 1,
 (5, 5): 3,
 (6, 5): 2,
 (7, 5): 2,
 (8, 5): 1,
 (9, 5): 1,
 (10, 5): 1,
 (11, 5): 1,
 (12, 5): 1,
 (1, 6): 1,
 (2, 6): 2,
 (3, 6): 1,
 (4, 6): 1,
 (5, 6): 2,
 (6, 6): 3,
 (7, 6): 1,
 (8, 6): 2,
 (9, 6): 1,
 (10, 6): 1,
 (11, 6): 1,
 (12, 6): 1,
 (1, 7): 1,
 (2, 7): 1,
 (3, 7): 2,
 (4, 7): 1,
 (5, 7): 2,
 (6, 7): 1,
 (7, 7): 3,
 (8, 7): 2,
 (9, 7): 1,
 (10, 7): 

## This function calculates the i-neighbourhood for the k-tuple k_t

In [9]:
import numpy as np
def get_i_neighbourhood_multiset(vertex, input_tuple, colour_dir=None):
    res = []
    for i in range(1, len(input_tuple)+1):
        j_neighbour = list(input_tuple)
        j_neighbour[i-1] = vertex
        j_neighbour = tuple(j_neighbour)
        colour_i_neighbour = colour_dir[j_neighbour]
        res.append(colour_i_neighbour)
    res.sort()
    return res

In [10]:
print(get_i_neighbourhood_multiset(10, (4,3), Initial_colourings_G))

[1, 1]


### This function calculates the number of each colour

In [11]:
def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

# Actual 2-FWL algorithm

In [15]:
def k_wl_update(list_tuples, initial_colourings):
    colour_list = [initial_colourings]
    
    for i in range(10): 
        #Get the amount for each colour from the last iteration
        colour_counter = get_colour_counter(colour_list[-1])
        print(colour_counter)

        #new_colour_list is the list with all the colours for all k-tuples from iteration t-1
        new_colour_list = {}

        #Injective_func is the function that maps a encoding to a number (1,2,3...).
        #If the encoding is not in the function, we add a new entry to it.
        injective_func = {}
        for list_elements in list_tuples:
            for elem in list_elements:
                new_colour = [colour_list[i][elem]]
                neighbourhoods = []

                #We calculate all j-neighbours and set them as tuples.
                for j in range(1,13):
                    j_neighbours = tuple(get_i_neighbourhood_multiset(j, elem, colour_list[i]))
                    neighbourhoods.append(j_neighbours)

                #This is the new encoding of the colour from iteration t-1 and the coloursetmultisets of neighbours from t-1
                #new_colour(v) = [c_t-1(v), {colour 1_neighbourhood}, {colour 2_neighbourhood}]
                new_colour.append(frozenset(tuple(neighbourhoods)))
                new_colour = tuple(new_colour)

                #Check if colour encoding is in injective_func
                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                
                #Get hash value for colour encoding
                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int+1
        #for key_item in injective_func.keys():
        #    print(key_item)
                
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func
                


In [16]:
colour_list, injective_function = k_wl_update(t_l, initial_colourings=Initial_colourings_G)


[100.  32.  12.]
[12. 52. 32. 48.]
[12.  8.  4. 32. 48. 32.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16. 16. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]


# Code for H

In [17]:
initial_colourings_H = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2]]

In [18]:
Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

In [19]:
colour_list, injective_function = k_wl_update(t_l, Initial_colourings_H)

[ 32.  12. 100.]
[12. 52. 32. 48.]
[12.  4. 32. 32. 40.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
