In [1]:
t_l = [[(j, i) for i in range(j,13)] for j in range(1,13)]
t_l

[[(1, 1),
  (1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (1, 11),
  (1, 12)],
 [(2, 2),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (2, 11),
  (2, 12)],
 [(3, 3),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (3, 11),
  (3, 12)],
 [(4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (4, 12)],
 [(5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11), (5, 12)],
 [(6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (6, 11), (6, 12)],
 [(7, 7), (7, 8), (7, 9), (7, 10), (7, 11), (7, 12)],
 [(8, 8), (8, 9), (8, 10), (8, 11), (8, 12)],
 [(9, 9), (9, 10), (9, 11), (9, 12)],
 [(10, 10), (10, 11), (10, 12)],
 [(11, 11), (11, 12)],
 [(12, 12)]]

In [2]:
initial_colourings_G = [
     [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [2, 0, 0, 0, 1, 0, 0, 0, 1, 0],
              [2, 0, 0, 0, 1, 0, 0, 0, 1],
                 [2, 1, 1, 0, 0, 0, 0, 0],
                    [2, 0, 1, 0, 0, 0, 0],
                       [2, 1, 0, 0, 0, 0],
                          [2, 0, 0, 0, 0],
                             [2, 1, 1, 0],
                                [2, 0, 1],
                                   [2, 1],
                                       [2]]

In [3]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c + 1

In [4]:
for elem_key in Initial_colourings_G.keys():
    if Initial_colourings_G[elem_key] == 1:
        print(elem_key)

(1, 2)
(1, 3)
(1, 4)
(1, 6)
(1, 7)
(1, 8)
(1, 10)
(1, 11)
(1, 12)
(2, 3)
(2, 4)
(2, 5)
(2, 7)
(2, 8)
(2, 9)
(2, 11)
(2, 12)
(3, 4)
(3, 5)
(3, 6)
(3, 8)
(3, 9)
(3, 10)
(3, 12)
(4, 5)
(4, 6)
(4, 7)
(4, 9)
(4, 10)
(4, 11)
(5, 8)
(5, 9)
(5, 10)
(5, 11)
(5, 12)
(6, 7)
(6, 9)
(6, 10)
(6, 11)
(6, 12)
(7, 9)
(7, 10)
(7, 11)
(7, 12)
(8, 9)
(8, 10)
(8, 11)
(8, 12)
(9, 12)
(10, 11)


In [5]:
def get_multiset_neighbourhood(input_set, colour_dir=None):
    res = []
    all_k_tuples = [(i,j) for i in range(1,13) for j in range(1,13) if i <= j] 
    for elem in all_k_tuples:
        if len(set(input_set).intersection(set(elem))) == len(input_set) - 1:
            res.append(colour_dir[elem])
    res.sort()
    return res

In [6]:
import numpy as np

def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

In [7]:
import numpy as np

def multiset_k_wl_update(list_tuples, initial_colourings):
    colour_list = [initial_colourings]
    for i in range(10): 
        print(get_colour_counter(colour_list[-1]))
        new_colour_list = {}
        injective_func = {}
        for list_elements in list_tuples:
            for elem in list_elements:
                new_colour = [colour_list[i][elem]]
                set_neighbourhood = tuple(get_multiset_neighbourhood(elem, colour_list[i]))

                #new_colour = [c_(t-1), {{c_(t-1)(v), v is set-neighbour}}]
                new_colour.append(tuple(set_neighbourhood))
                new_colour = tuple(new_colour)
                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int+1
                
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func

In [8]:
colour_list, injective_function = multiset_k_wl_update(t_l, initial_colourings=Initial_colourings_G)

[50. 16. 12.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]


In [11]:
initial_colourings_H = [
     [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
              [2, 0, 0, 0, 1, 0, 0, 1, 0],
                 [2, 1, 1, 0, 0, 0, 0, 0],
                    [2, 0, 1, 0, 0, 0, 0],
                       [2, 1, 0, 0, 0, 0],
                          [2, 0, 0, 0, 0],
                             [2, 1, 1, 0],
                                [2, 0, 1],
                                   [2, 1],
                                       [2]]

Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

In [12]:
colour_list, injective_function = multiset_k_wl_update(t_l, Initial_colourings_H)

[16. 12. 50.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
