In [140]:
import numpy as np

t_l = [[(i,j) for i in range(1,13)] for j in range(1,13)]
t_l

[[(1, 1),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 1),
  (6, 1),
  (7, 1),
  (8, 1),
  (9, 1),
  (10, 1),
  (11, 1),
  (12, 1)],
 [(1, 2),
  (2, 2),
  (3, 2),
  (4, 2),
  (5, 2),
  (6, 2),
  (7, 2),
  (8, 2),
  (9, 2),
  (10, 2),
  (11, 2),
  (12, 2)],
 [(1, 3),
  (2, 3),
  (3, 3),
  (4, 3),
  (5, 3),
  (6, 3),
  (7, 3),
  (8, 3),
  (9, 3),
  (10, 3),
  (11, 3),
  (12, 3)],
 [(1, 4),
  (2, 4),
  (3, 4),
  (4, 4),
  (5, 4),
  (6, 4),
  (7, 4),
  (8, 4),
  (9, 4),
  (10, 4),
  (11, 4),
  (12, 4)],
 [(1, 5),
  (2, 5),
  (3, 5),
  (4, 5),
  (5, 5),
  (6, 5),
  (7, 5),
  (8, 5),
  (9, 5),
  (10, 5),
  (11, 5),
  (12, 5)],
 [(1, 6),
  (2, 6),
  (3, 6),
  (4, 6),
  (5, 6),
  (6, 6),
  (7, 6),
  (8, 6),
  (9, 6),
  (10, 6),
  (11, 6),
  (12, 6)],
 [(1, 7),
  (2, 7),
  (3, 7),
  (4, 7),
  (5, 7),
  (6, 7),
  (7, 7),
  (8, 7),
  (9, 7),
  (10, 7),
  (11, 7),
  (12, 7)],
 [(1, 8),
  (2, 8),
  (3, 8),
  (4, 8),
  (5, 8),
  (6, 8),
  (7, 8),
  (8, 8),
  (9, 8),
  (10, 8),
  (11, 8),
  (12, 8)],
 [(1, 9)

In [2]:
initial_colourings_G = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2]]

In [3]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c+1

In [5]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c+1

In [6]:
Initial_colourings_G

{(1, 1): 3,
 (2, 1): 1,
 (3, 1): 1,
 (4, 1): 1,
 (5, 1): 2,
 (6, 1): 1,
 (7, 1): 1,
 (8, 1): 1,
 (9, 1): 2,
 (10, 1): 1,
 (11, 1): 1,
 (12, 1): 1,
 (1, 2): 1,
 (2, 2): 3,
 (3, 2): 1,
 (4, 2): 1,
 (5, 2): 1,
 (6, 2): 2,
 (7, 2): 1,
 (8, 2): 1,
 (9, 2): 1,
 (10, 2): 2,
 (11, 2): 1,
 (12, 2): 1,
 (1, 3): 1,
 (2, 3): 1,
 (3, 3): 3,
 (4, 3): 1,
 (5, 3): 1,
 (6, 3): 1,
 (7, 3): 2,
 (8, 3): 1,
 (9, 3): 1,
 (10, 3): 1,
 (11, 3): 2,
 (12, 3): 1,
 (1, 4): 1,
 (2, 4): 1,
 (3, 4): 1,
 (4, 4): 3,
 (5, 4): 1,
 (6, 4): 1,
 (7, 4): 1,
 (8, 4): 2,
 (9, 4): 1,
 (10, 4): 1,
 (11, 4): 1,
 (12, 4): 2,
 (1, 5): 2,
 (2, 5): 1,
 (3, 5): 1,
 (4, 5): 1,
 (5, 5): 3,
 (6, 5): 2,
 (7, 5): 2,
 (8, 5): 1,
 (9, 5): 1,
 (10, 5): 1,
 (11, 5): 1,
 (12, 5): 1,
 (1, 6): 1,
 (2, 6): 2,
 (3, 6): 1,
 (4, 6): 1,
 (5, 6): 2,
 (6, 6): 3,
 (7, 6): 1,
 (8, 6): 2,
 (9, 6): 1,
 (10, 6): 1,
 (11, 6): 1,
 (12, 6): 1,
 (1, 7): 1,
 (2, 7): 1,
 (3, 7): 2,
 (4, 7): 1,
 (5, 7): 2,
 (6, 7): 1,
 (7, 7): 3,
 (8, 7): 2,
 (9, 7): 1,
 (10, 7): 

## This is the fuction that calculates the multisets for a $k$-tuple according to definition 3 in my thesis

In [204]:
def multiset_set_function(input_arr):
    elem_list = [tuple(input_arr)]
    
    for elem in input_arr:
        new_elem = list(input_arr)[:]
        new_elem.append(elem)
        new_elem.sort()
        if len(set(new_elem)) == len(input_arr):
            elem_list.append(tuple(new_elem))
    
    return elem_list

In [205]:
print(multiset_set_function([1,2]))

[(1, 2), (1, 1, 2), (1, 2, 2)]


## This is function f by definition 5

In [206]:
def shrinking_function(input_arr):
    new_list = list(input_arr)[:]
    if len(input_arr) > 2:
        counts = dict() 
        for i in input_arr:
            counts[i] = counts.get(i, 0) + 1
        for key in counts.keys():
            if counts[key] >= 2:
                counts[key] -= 1
        new_list = []
        for key in counts.keys():
            for i in range(counts[key]):
                new_list.append(key)
    return tuple(new_list)


In [207]:
print(shrinking_function(("v1", "v1", "v1", "v2", "v3", "v3")))

('v1', 'v1', 'v2', 'v3')


## Multiset Neighbourhood defined as in the paper

In [208]:
def get_neighbourhood_for_multiset(input_multiset):
    if len(input_multiset) == 2:
        all_k_multisets = [(i,j) for i in range(1, 13) for j in range(i, 13)]
    elif len(input_multiset) == 3:
        all_k_multisets = [(i,j,k) for i in range(1,13) for j in range(i,13) for k in range(j, 13)]
    res = []
    for elem in all_k_multisets: 
        if len(set(input_multiset).intersection(set(elem))) == len(input_multiset) - 1:
            if len(set(elem)) <= 2:
                if (len(elem) == 2) or (len(shrinking_function(elem)) == 2):
                    res.append(elem)
    return res

In [209]:

import itertools
def get_permutations(input_tuple):
    all_perms = list(itertools.permutations(input_tuple))    
    return all_perms



In [210]:
def get_colour_arr(arr, colour_dir):
    res = []
    for elem in arr:
        res.append(colour_dir[elem])
    res.sort()
    return res

In [211]:
def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

In [212]:
def TM_k_wl_update(list_tuples, initial_colourings):
    colour_list = [initial_colourings]

    for i in range(5):
        colour_counter = get_colour_counter(colour_list[-1])
        print(colour_counter)
        new_colour_list= {}

        injective_func = {}

        for h, list_elements in enumerate(list_tuples):
            for j, elem in enumerate(list_elements):
                new_colour = [colour_list[i][elem]]
                neighbourhoods = []
                multiset_sets = multiset_set_function(elem)
                for multiset_elem in multiset_sets: 
                    neighbours_elements = get_neighbourhood_for_multiset(multiset_elem)
                    neighbour_list = []
                    for neighbours in neighbours_elements:
                        new_elem = shrinking_function(neighbours)
                        # print(f"elem = {elem}")
                        all_neighbour_perms = get_permutations(new_elem)
                        neighbour_list += all_neighbour_perms

                    neighbour_colour_list = get_colour_arr(neighbour_list, colour_list[i])
                    neighbourhoods.append(tuple(neighbour_colour_list))
               
                new_colour.append(frozenset(tuple(neighbourhoods)))
                new_colour = tuple(new_colour)

                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                

                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int + 1
        
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func
                

In [200]:
colour_list, injective_function = TM_k_wl_update(t_l, initial_colourings=Initial_colourings_G)

[100.  32.  12.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]


In [201]:
initial_colourings_H = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2]]

In [202]:
Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

In [203]:
colour_list, injective_function = TM_k_wl_update(t_l, Initial_colourings_H)

[ 32.  12. 100.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]
[ 4. 12. 16. 48.  8. 16. 40.]
