# This is the $2$-FWL code applied to the non-isomorphic graph pair $G$ and $H$.

### First, we create all possible 2-tuples.

In [1]:
import numpy as np

t_l = [[(i,j) for i in range(1,13)] for j in range(1,13)]

## This function calculates the i-neighbourhood for a k-tuple k, where i is a vertex of $G$.

In [2]:
import numpy as np
def get_i_neighbourhood_tuples(vertex, input_tuple, colour_dir=None):
    res = []
    for i in range(1, len(input_tuple)+1):
        j_neighbour = list(input_tuple)
        j_neighbour[i-1] = vertex
        j_neighbour = tuple(j_neighbour)
        colour_i_neighbour = colour_dir[j_neighbour]
        res.append(colour_i_neighbour)
    res.sort()
    return res

### This function calculates the number of each colour, this methods helps evaluating the cardinalities of all colours

In [3]:
def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

## Encoding of the 2-FWL algorithm

In [5]:
def k_fwl_update(list_tuples, initial_colourings, iterations = 10):
    colour_list = [initial_colourings]
    
    for i in range(iterations): 
        #Get the amount for each colour from the last iteration
        colour_counter = get_colour_counter(colour_list[-1])
        print(colour_counter)

        #new_colour_list is the list with all the colour cardinalities for all k-tuples from iteration t-1
        new_colour_list = {}

        #Injective_func is the function that maps a encoding to a number (1,2,3...).
        #If the encoding is not in the function, we add a new entry to it.
        injective_func = {}
        for list_elements in list_tuples:
            for elem in list_elements:
                new_colour = [colour_list[i][elem]]
                neighbourhoods = []

                #We calculate all j-neighbours and set them as tuples.
                for j in range(1,13):
                    j_neighbours = tuple(get_i_neighbourhood_tuples(j, elem, colour_list[i]))
                    neighbourhoods.append(j_neighbours)

                #This is the new encoding of the colour from iteration t-1 and the coloursetmultisets of neighbours from t-1
                #new_colour(v) = [c_t-1(v), {colour 1_neighbourhood}, {colour 2_neighbourhood}]
                new_colour.append(frozenset(tuple(neighbourhoods)))
                new_colour = tuple(new_colour)

                #Check if colour encoding is in injective_func
                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                
                #Get hash value for colour encoding
                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int+1
                
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func
                




# Code for G

## Atomic types for the 2-tuples of $G$.

In [6]:
initial_colourings_G = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2]]

### This following function maps each atomic type to its according 2-tuple.

In [7]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c+1



### Return of the colour cardinalities for graph $G$ for 10 iterations. We can see after 5 iterations the 2-FWL has calculated a stable colouring.

In [8]:
colour_list, injective_function = k_fwl_update(t_l, initial_colourings=Initial_colourings_G, iterations=10)


[100.  32.  12.]
[12. 52. 32. 48.]
[12.  8.  4. 32. 48. 32.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16. 16. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]
[ 4.  8.  4. 16. 32. 16.  8. 16.  8.  8. 16.  8.]


# Code for H
## Atomic Types for 2-tuples.

In [9]:
initial_colourings_H = [
    [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2]]

### This following function maps each atomic type to its according 2-tuple.

In [10]:
Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

### Return of the colour cardinalities for graph $H$ for 10 iterations. We can see that after 4 iterations the 2-FWL has calculated a stable colouring for $H$. Since in iteration 2 the cardinalities differ from those determined in $G$, the 2-FWL returns that the graphs are non-isomorphic. 

In [12]:
colour_list, injective_function = k_fwl_update(t_l, Initial_colourings_H, iterations=10)

[ 32.  12. 100.]
[12. 52. 32. 48.]
[12.  4. 32. 32. 40.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
[ 4.  4.  8. 16. 16. 16. 16.  8.  8.  8.  8.  8.  8. 16.]
