# This is the M-2-WL code applied to the non-isomorphic graph pair $G$ and $H$.

### First, we create all possible multisets of length 2.

In [1]:
t_l = [[(j, i) for i in range(j,13)] for j in range(1,13)]

## This function calculates the multiset neighbourhood for a given multiset. 

In [11]:
def get_multiset_neighbourhood(input_set, colour_dir=None):
    res = []
    all_k_multisets = [(i,j) for i in range(1,13) for j in range(1,13) if i <= j] 
    for elem in all_k_multisets:
        if len(set(input_set).intersection(set(elem))) == len(input_set) - 1:
            res.append(colour_dir[elem])
    res.sort()
    return res

## This function calculates the number of each colour in from the whole graph, determining the cardinality of all colours.

In [12]:
import numpy as np

def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

## Encoding of the M-2-WL

In [4]:
def multiset_k_wl_update(list_tuples, initial_colourings, iterations=10):
    colour_list = [initial_colourings]
    for i in range(iterations): 
        print(get_colour_counter(colour_list[-1]))
        new_colour_list = {}
        injective_func = {}
        for list_elements in list_tuples:
            for elem in list_elements:
                new_colour = [colour_list[i][elem]]
                set_neighbourhood = tuple(get_multiset_neighbourhood(elem, colour_list[i]))

                #new_colour = [c_(t-1), {{c_(t-1)(v), v is set-neighbour}}]
                new_colour.append(tuple(set_neighbourhood))
                new_colour = tuple(new_colour)
                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int+1
                
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func

# Code for G

## Atomic types of the 2-multisets for $G$.

In [5]:
initial_colourings_G = [
     [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [2, 0, 0, 0, 1, 0, 0, 0, 1, 0],
              [2, 0, 0, 0, 1, 0, 0, 0, 1],
                 [2, 1, 1, 0, 0, 0, 0, 0],
                    [2, 0, 1, 0, 0, 0, 0],
                       [2, 1, 0, 0, 0, 0],
                          [2, 0, 0, 0, 0],
                             [2, 1, 1, 0],
                                [2, 0, 1],
                                   [2, 1],
                                       [2]]

### This following function maps each atomic type to its according 2-multiset.

In [6]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G,):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c + 1

### Return of the colour cardinalities for graph $G$ for 10 iterations. After 1 iteration the algorithm has computed a stable colouring.

In [7]:
colour_list, injective_function = multiset_k_wl_update(t_l, initial_colourings=Initial_colourings_G, iterations=10)

[50. 16. 12.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]


# Code for $H$

## Atomic types of the 2-multisets for $H$.

In [8]:
initial_colourings_H = [
     [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
              [2, 0, 0, 0, 1, 0, 0, 1, 0],
                 [2, 1, 1, 0, 0, 0, 0, 0],
                    [2, 0, 1, 0, 0, 0, 0],
                       [2, 1, 0, 0, 0, 0],
                          [2, 0, 0, 0, 0],
                             [2, 1, 1, 0],
                                [2, 0, 1],
                                   [2, 1],
                                       [2]]

### This following function maps each atomic type to its according 2-multiset.

In [14]:
Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

### Return of the colour cardinalities for graph $H$ for 10 iterations. After 1 iteration the algorithm has computed a stable colouring, which is the same as for $G$. The M-2-WL therefore fails to distinguish $G$ and $H$.

In [9]:
colour_list, injective_function = multiset_k_wl_update(t_l, Initial_colourings_H)

[16. 12. 50.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
[ 4.  6.  8. 24.  8.  8. 20.]
