# This is the S-2-WL code applied to the non-isomorphic graph pair $G$ and $H$ from chapter 4.5.

### First, we create all sets of length 2.

In [1]:
t_l = [[(j, i) for i in range(j+1,13)] for j in range(1,12)]

## This function determines the neighbourhood for a $k$-set.

In [4]:
def get_set_neighbourhood(input_set, colour_dir=None):
    res = []
    all_k_sets = [(i,j) for i in range(1,13) for j in range(1,13) if i < j] 
    for elem in all_k_sets:
        if len(set(input_set).intersection(set(elem))) == len(input_set) - 1:
            res.append(colour_dir[elem])
    res.sort()
    return res

### This function calculates the number of each colour, this methods helps evaluating the cardinalities of all colours

In [6]:
import numpy as np

def get_colour_counter(dic_colour):
    all_colours = []
    for key_item in dic_colour.keys():
        all_colours.append(dic_colour[key_item])
    res = np.zeros(len(set(all_colours)))
    for elem in all_colours:
        res[elem-1] += 1
    return res

## Encoding of the S-2-WL

In [7]:
def set_k_wl_update(list_tuples, initial_colourings):
    colour_list = [initial_colourings]
    for i in range(10): 
        print(get_colour_counter(colour_list[-1]))
        new_colour_list = {}
        injective_func = {}
        for list_elements in list_tuples:
            for elem in list_elements:
                new_colour = [colour_list[i][elem]]
                set_neighbourhood = tuple(get_set_neighbourhood(elem, colour_list[i]))

                #new_colour = [c_(t-1), {{c_(t-1)(v), v is set-neighbour}}]
                new_colour.append(tuple(set_neighbourhood))
                new_colour = tuple(new_colour)
                if new_colour not in injective_func.keys():
                    injective_func[new_colour] = len(injective_func)
                
                new_colour_int = injective_func[new_colour]
                new_colour_list[elem] = new_colour_int+1
                
        colour_list.append(new_colour_list)
    return colour_list[-1], injective_func

# Code for graph $G$.

## Atomic types for the $k$-sets of $G$.

In [2]:
initial_colourings_G = [
     [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0, 0, 0, 1],
                 [1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0],
                       [1, 0, 0, 0, 0],
                          [0, 0, 0, 0],
                             [1, 1, 0],
                                [0, 1],
                                   [1]]


### This following function maps each atomic type to its according 2-set.

In [3]:
Initial_colourings_G = {}

for tupled, colour_list in zip(t_l, initial_colourings_G):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_G[t] = c + 1

### Return of the colour cardinalities for graph $G$ for 10 iterations. We can see that after 2 iterations, the S-2-WL has determined a stable colouring.

In [8]:
colour_list, injective_function = set_k_wl_update(t_l, initial_colourings=Initial_colourings_G)

[50. 16.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]


# Graph H

## Atomic types for all 2-sets in $H$.

In [9]:
initial_colourings_H = [
     [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0, 1],
              [0, 0, 0, 1, 0, 0, 1, 0],
                 [1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0],
                       [1, 0, 0, 0, 0],
                          [0, 0, 0, 0],
                             [1, 1, 0],
                                [0, 1],
                                   [1]]

### This following function maps each atomic type to its according 2-set.

In [10]:
Initial_colourings_H = {}

for tupled, colour_list in zip(t_l, initial_colourings_H):
    for t, c in zip(tupled, colour_list):
        Initial_colourings_H[t] = c

### Return of the colour cardinalities for the S-2-WL for $H$. Again, it has calculated the same stable colouring after 2 iterations as done for $G$. Therefore, the S-2-WL fails to distinguish $G$ and $H$.

In [11]:
colour_list, injective_function = set_k_wl_update(t_l, Initial_colourings_H)

[16. 50.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
[ 6.  8. 24.  8. 20.]
